---
vignette: >
  %\VignetteIndexEntry{atime}
  %\VignetteEngine{litedown::vignette}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
litedown::reactor(
  collapse = TRUE,
  comment = "#>",
  fig.width=10,
  fig.height=6)
data.table::setDTthreads(1)
```

The goal of this vignette is to give some examples of how to benchmark the C++ code.

```{r}
## increase text size in all figures.
if(require(ggplot2))theme_set(theme_bw()+theme(text=element_text(size=15)))

result_list <- atime::atime(
  N=10^seq(3, 6, by=0.2),
  setup={
    N_points <- N
    N_queries <- N
    dataScale <- 10
    N_list <- Poncatime:::generatePointClouds_interface(N_points, N_queries, dataScale)
    status <- Poncatime:::buildKdTree_interface(N_list$points)
  },
  planeFit=Poncatime:::planeFit_interface(N_list$queries, dataScale/5),
  planeFitK=Poncatime:::planeFitK_interface(N_list$queries, 10),
  ## setup={
  ##   N_points <- N
  ##   N_queries <- N
  ##   dataScale <- 10
  ##   N_list <- Poncatime:::generatePointClouds_interface(N_points, N_queries, dataScale)
  ##   status <- Poncatime:::buildKdTree_interface(N_list$points)
  ## },
  seconds.limit=0.1,
  result=TRUE,
  ##asoCurvatureEstimation=with(N_list, Poncatime:::planeFit_interface(queries, dataScale/5))
)
plot(result_list)

ref_list <- atime::references_best(result_list)
plot(ref_list)

pred_list <- predict(ref_list)
plot(pred_list)
```
