// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// asoCurvatureEstimation_interface
int asoCurvatureEstimation_interface(const Eigen::MatrixXd& points, const Eigen::MatrixXd& queries, const double scale);
RcppExport SEXP _Poncatime_asoCurvatureEstimation_interface(SEXP pointsSEXP, SEXP queriesSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type queries(queriesSEXP);
    Rcpp::traits::input_parameter< const double >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(asoCurvatureEstimation_interface(points, queries, scale));
    return rcpp_result_gen;
END_RCPP
}
// generate_data_interface
void generate_data_interface(const Eigen::MatrixXd& points, const Eigen::MatrixXd& queries, double dataScale);
RcppExport SEXP _Poncatime_generate_data_interface(SEXP pointsSEXP, SEXP queriesSEXP, SEXP dataScaleSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type queries(queriesSEXP);
    Rcpp::traits::input_parameter< double >::type dataScale(dataScaleSEXP);
    generate_data_interface(points, queries, dataScale);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Poncatime_asoCurvatureEstimation_interface", (DL_FUNC) &_Poncatime_asoCurvatureEstimation_interface, 3},
    {"_Poncatime_generate_data_interface", (DL_FUNC) &_Poncatime_generate_data_interface, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_Poncatime(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
