// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// asoCurvatureEstimation_interface
Rcpp::IntegerVector asoCurvatureEstimation_interface(const Rcpp::NumericVector pointVec, const Rcpp::NumericVector queriesVec, const double scale);
RcppExport SEXP _Poncatime_asoCurvatureEstimation_interface(SEXP pointVecSEXP, SEXP queriesVecSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type pointVec(pointVecSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type queriesVec(queriesVecSEXP);
    Rcpp::traits::input_parameter< const double >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(asoCurvatureEstimation_interface(pointVec, queriesVec, scale));
    return rcpp_result_gen;
END_RCPP
}
// generate_data_interface
Rcpp::List generate_data_interface(const int N_data, const int N_queries, double dataScale);
RcppExport SEXP _Poncatime_generate_data_interface(SEXP N_dataSEXP, SEXP N_queriesSEXP, SEXP dataScaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type N_data(N_dataSEXP);
    Rcpp::traits::input_parameter< const int >::type N_queries(N_queriesSEXP);
    Rcpp::traits::input_parameter< double >::type dataScale(dataScaleSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_data_interface(N_data, N_queries, dataScale));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Poncatime_asoCurvatureEstimation_interface", (DL_FUNC) &_Poncatime_asoCurvatureEstimation_interface, 3},
    {"_Poncatime_generate_data_interface", (DL_FUNC) &_Poncatime_generate_data_interface, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_Poncatime(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
