// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// generatePointClouds_interface
Rcpp::List generatePointClouds_interface(const int N_data, const int N_queries, const double dataScale);
RcppExport SEXP _Poncatime_generatePointClouds_interface(SEXP N_dataSEXP, SEXP N_queriesSEXP, SEXP dataScaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type N_data(N_dataSEXP);
    Rcpp::traits::input_parameter< const int >::type N_queries(N_queriesSEXP);
    Rcpp::traits::input_parameter< const double >::type dataScale(dataScaleSEXP);
    rcpp_result_gen = Rcpp::wrap(generatePointClouds_interface(N_data, N_queries, dataScale));
    return rcpp_result_gen;
END_RCPP
}
// buildKdTree_interface
bool buildKdTree_interface(const Eigen::MatrixXd& points);
RcppExport SEXP _Poncatime_buildKdTree_interface(SEXP pointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type points(pointsSEXP);
    rcpp_result_gen = Rcpp::wrap(buildKdTree_interface(points));
    return rcpp_result_gen;
END_RCPP
}
// asoCurvatureEstimationK_interface
Rcpp::DataFrame asoCurvatureEstimationK_interface(const Eigen::MatrixXd& queries, const int k);
RcppExport SEXP _Poncatime_asoCurvatureEstimationK_interface(SEXP queriesSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type queries(queriesSEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(asoCurvatureEstimationK_interface(queries, k));
    return rcpp_result_gen;
END_RCPP
}
// planeFitK_interface
Rcpp::DataFrame planeFitK_interface(const Eigen::MatrixXd& queries, const int k);
RcppExport SEXP _Poncatime_planeFitK_interface(SEXP queriesSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type queries(queriesSEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(planeFitK_interface(queries, k));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Poncatime_generatePointClouds_interface", (DL_FUNC) &_Poncatime_generatePointClouds_interface, 3},
    {"_Poncatime_buildKdTree_interface", (DL_FUNC) &_Poncatime_buildKdTree_interface, 1},
    {"_Poncatime_asoCurvatureEstimationK_interface", (DL_FUNC) &_Poncatime_asoCurvatureEstimationK_interface, 2},
    {"_Poncatime_planeFitK_interface", (DL_FUNC) &_Poncatime_planeFitK_interface, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_Poncatime(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
