# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

generatePointClouds_interface <- function(N_data, N_queries, dataScale) {
    .Call('_Poncatime_generatePointClouds_interface', PACKAGE = 'Poncatime', N_data, N_queries, dataScale)
}

buildKdTree_interface <- function(points) {
    .Call('_Poncatime_buildKdTree_interface', PACKAGE = 'Poncatime', points)
}

asoCurvatureEstimation_interface <- function(queries, scale) {
    .Call('_Poncatime_asoCurvatureEstimation_interface', PACKAGE = 'Poncatime', queries, scale)
}

planeFit_interface <- function(queries, scale) {
    .Call('_Poncatime_planeFit_interface', PACKAGE = 'Poncatime', queries, scale)
}

