# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

asoCurvatureEstimation_interface <- function(points, queries, scale) {
    .Call('_Poncatime_asoCurvatureEstimation_interface', PACKAGE = 'Poncatime', points, queries, scale)
}

generate_data_interface <- function(points, queries, dataScale) {
    invisible(.Call('_Poncatime_generate_data_interface', PACKAGE = 'Poncatime', points, queries, dataScale))
}

