# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

asoCurvatureEstimation_interface <- function(pointVec, queriesVec, scale) {
    .Call('_Poncatime_asoCurvatureEstimation_interface', PACKAGE = 'Poncatime', pointVec, queriesVec, scale)
}

generate_data_interface <- function(N_data, N_queries, dataScale) {
    .Call('_Poncatime_generate_data_interface', PACKAGE = 'Poncatime', N_data, N_queries, dataScale)
}

